package com.example.zingmp3phake.utils

const val API_TRENDING_ZING_SONG =
    "https://mp3.zing.vn/xhr/chart-realtime?songId=0&videoId=0&albumId=0&chart=song&time=-1"
const val API_ZING_SONG = "https://mp3.zing.vn/xhr/media/get-source?type=audio&key="
const val API_BASE_SPOTIFY = "https://spotify23.p.rapidapi.com/"
const val API_KEY = "X-RapidAPI-Key"
const val API_HOST = "X-RapidAPI-Host"
const val API_OPTION = "&type=tracks&offset=0&limit=10&numberOfTopResults=5"
const val METHOD_GET = "GET"
const val ZING_SONG_ID = "code"
const val ZING_SONG_NAME = "title"
const val ZING_SONG_ARTIST = "artists_names"
const val ZING_SONG_DURATION = "duration"
const val ZING_SONG_IMG = "thumbnail"
const val ZING_SONG_SOURCE = "source"
const val ZING_SONG_ALBUM = "album"
const val ZING_SONG_URL = "128"
const val ZING_SONG = "song"
const val ZING_DATA = "data"
const val SPOTIFY_LINE = "lines"
const val SPOTIFY_WORD = "words"
const val SPOTIFY_LYRIC = "lyrics"
const val SPOTIFY_TRACK = "tracks"
